# Generated by fix — order_number field needs max_length=30
# to fit WFD-YYYYMMDD-XXXXXXXX (21 chars) with headroom.
# The original migration (0001_initial) only allowed max_length=20.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
